sudo: required

language: ruby

services:
  - postgresql
  - redis

before_script:
  - gem install bundler
  - bundle install
  - RACK_ENV=test rake db:create
  - RACK_ENV=test rake db:migrate

script:
  - rspec

